;;; test-static-analysis.el --- Static analysis tests for Elisp codebases -*- lexical-binding: t; -*-

;; Copyright (C) 2024 Jingtao Xu

;; Author: Jingtao Xu
;; Keywords: tests

;;; Commentary:

;; General-purpose static analysis tests for Elisp codebases.
;; These tests dynamically extract all definitions from source files and verify
;; they are properly bound after loading.
;;
;; Key features:
;; - Automatically discovers all defun, defvar, defcustom, cl-defstruct, etc.
;; - Works with literate .org files containing elisp code blocks
;; - No hardcoded symbol lists - adapts to any Elisp codebase
;; - Catches accidentally deleted functions/variables
;;
;; Best practices implemented:
;; 1. Parse source to extract defined symbols (not hardcoded lists)
;; 2. Verify all extracted symbols are bound after loading
;; 3. Byte-compile with strict warnings to catch undefined references
;; 4. Use check-declare to verify declare-function statements
;;
;; References:
;; - https://github.com/Wilfred/elisp-def
;; - https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Variables.html
;; - https://alphapapa.github.io/emacs-package-dev-handbook/

;;; Code:

(require 'ert)
(require 'bytecomp)
(require 'check-declare)
(require 'cl-lib)

;;; ============================================================================
;;; Symbol Extraction - Parse elisp source to find all definitions
;;; ============================================================================

(defvar test-static--definition-forms
  '(;; Functions
    defun defmacro defsubst cl-defun cl-defmacro cl-defsubst
    defadvice define-advice
    ;; Variables
    defvar defconst defcustom defvar-local
    ;; Structures (generate multiple symbols)
    cl-defstruct
    ;; Modes (generate function + variable)
    define-minor-mode define-globalized-minor-mode define-derived-mode
    define-generic-mode
    ;; Other definitions
    defface defgroup defalias define-error
    cl-defgeneric cl-defmethod)
  "List of forms that define symbols.
These are the car of top-level forms we look for when extracting definitions.")

(defun test-static--extract-elisp-from-org (org-file)
  "Extract all elisp source code from ORG-FILE.
Returns a string containing concatenated elisp code blocks."
  (with-temp-buffer
    (insert-file-contents org-file)
    (goto-char (point-min))
    (let ((code-blocks nil))
      ;; Find all elisp source blocks
      (while (re-search-forward
              "^[ \t]*#\\+BEGIN_SRC[ \t]+elisp\\(?:[ \t].*\\)?$" nil t)
        (let ((start (line-beginning-position 2)))
          (when (re-search-forward "^[ \t]*#\\+END_SRC" nil t)
            (push (buffer-substring-no-properties
                   start (line-beginning-position))
                  code-blocks))))
      (mapconcat #'identity (nreverse code-blocks) "\n"))))

(defun test-static--extract-definitions-from-string (elisp-string)
  "Extract all symbol definitions from ELISP-STRING.
Returns an alist of (TYPE . SYMBOL-NAME) for each definition found.
TYPE is the defining form (defun, defvar, cl-defstruct, etc.)."
  (with-temp-buffer
    (insert elisp-string)
    (goto-char (point-min))
    (let ((definitions nil))
      (condition-case nil
          (while t
            (let ((form (read (current-buffer))))
              (when (and (listp form)
                         (symbolp (car form))
                         (memq (car form) test-static--definition-forms))
                (let ((type (car form))
                      (name (cadr form)))
                  ;; Handle different definition types
                  (cond
                   ;; cl-defstruct - extracts struct name
                   ((eq type 'cl-defstruct)
                    (let ((struct-name (if (listp name) (car name) name)))
                      (push (cons type struct-name) definitions)))
                   ;; Standard definitions - just use name
                   ((symbolp name)
                    (push (cons type name) definitions))
                   ;; Quoted name (defalias 'foo ...)
                   ((and (listp name) (eq (car name) 'quote))
                    (push (cons type (cadr name)) definitions)))))))
        (end-of-file nil))
      (nreverse definitions))))

(defun test-static--get-struct-generated-symbols (struct-name struct-def)
  "Get symbols generated by cl-defstruct for STRUCT-NAME.
STRUCT-DEF is the full struct definition form.
Returns list of (TYPE . SYMBOL) for constructor, predicate, accessors, etc."
  (let* ((symbols nil)
         (name-and-options (cadr struct-def))
         ;; Options are keyword-value pairs in the list after struct name
         ;; e.g., (claude-agent-text-block (:constructor foo) (:copier nil))
         (options-list (when (listp name-and-options) (cdr name-and-options)))
         (slots (if (listp name-and-options)
                    (cddr struct-def)
                  (cddr struct-def)))
         ;; Parse options into a plist
         (options-plist (apply #'append
                               (mapcar (lambda (opt)
                                         (when (and (listp opt) (keywordp (car opt)))
                                           (list (car opt) (cadr opt))))
                                       options-list))))
    ;; Constructor: make-NAME or custom via :constructor (nil means no constructor)
    (let ((constructor-opt (plist-member options-plist :constructor)))
      (cond
       ;; :constructor nil - no constructor
       ((and constructor-opt (null (cadr constructor-opt)))
        nil)
       ;; :constructor NAME - custom constructor name
       ((and constructor-opt (cadr constructor-opt))
        (push (cons 'defun (cadr constructor-opt)) symbols))
       ;; No :constructor option - default make-NAME
       (t
        (push (cons 'defun (intern (format "make-%s" struct-name))) symbols))))
    ;; Predicate: NAME-p
    (push (cons 'defun (intern (format "%s-p" struct-name))) symbols)
    ;; Copier: copy-NAME (unless :copier nil)
    (let ((copier-opt (plist-member options-plist :copier)))
      (unless (and copier-opt (null (cadr copier-opt)))
        (push (cons 'defun (intern (format "copy-%s" struct-name))) symbols)))
    ;; Slot accessors: NAME-SLOT for each slot
    (dolist (slot slots)
      (let ((slot-name (if (listp slot) (car slot) slot)))
        (when (symbolp slot-name)
          (push (cons 'defun (intern (format "%s-%s" struct-name slot-name)))
                symbols))))
    symbols))

(defun test-static--get-mode-generated-symbols (mode-name)
  "Get symbols generated by define-minor-mode for MODE-NAME.
Returns list of (TYPE . SYMBOL) for the mode function.
Note: Mode variables are only bound when the mode is activated,
so we only check the function exists."
  (list
   ;; Mode function - the primary thing we can verify
   (cons 'defun mode-name)))

(defun test-static--expand-definitions (definitions elisp-string)
  "Expand DEFINITIONS to include generated symbols.
For cl-defstruct, adds constructor, predicate, accessors.
For define-minor-mode, adds hook, map, etc.
ELISP-STRING is the source for re-parsing struct definitions."
  (let ((expanded nil))
    (dolist (def definitions)
      (let ((type (car def))
            (name (cdr def)))
        (cond
         ;; cl-defstruct generates multiple symbols
         ((eq type 'cl-defstruct)
          ;; Re-read the struct definition to get slots
          (with-temp-buffer
            (insert elisp-string)
            (goto-char (point-min))
            (let ((found-struct nil))
              (condition-case nil
                  (while (not found-struct)
                    (let ((form (read (current-buffer))))
                      (when (and (listp form)
                                 (eq (car form) 'cl-defstruct)
                                 (let ((sname (cadr form)))
                                   (eq (if (listp sname) (car sname) sname) name)))
                        (setq expanded
                              (append (test-static--get-struct-generated-symbols
                                       name form)
                                      expanded))
                        (setq found-struct t))))
                (end-of-file nil)))))
         ;; define-minor-mode generates function + variables
         ((memq type '(define-minor-mode define-globalized-minor-mode))
          (setq expanded (append (test-static--get-mode-generated-symbols name)
                                 expanded)))
         ;; define-derived-mode generates function + variables
         ((eq type 'define-derived-mode)
          (setq expanded (append (test-static--get-mode-generated-symbols name)
                                 expanded)))
         ;; Standard definition
         (t
          (push def expanded)))))
    expanded))

;;; ============================================================================
;;; Project Discovery
;;; ============================================================================

(defun test-static--find-project-root ()
  "Find the project root directory."
  (or (locate-dominating-file default-directory "claude-agent.org")
      (locate-dominating-file default-directory ".git")
      default-directory))

(defvar test-static--source-files
  '("claude-agent.org" "claude-org.org" "emacs-mcp-server.org")
  "List of .org source files to analyze.
Customize this for your project.")

(defvar test-static--skip-files-without-deps t
  "If non-nil, skip files that fail to load due to missing dependencies.
This allows lint to run even without optional dependencies like web-server.")

(defun test-static--find-org-source-files (root)
  "Find all .org files containing elisp in ROOT directory.
Excludes test files and documentation."
  (let ((files nil))
    (dolist (file test-static--source-files)
      (let ((path (expand-file-name file root)))
        (when (file-exists-p path)
          (push path files))))
    (nreverse files)))

(defun test-static--can-load-file-p (file)
  "Test if FILE can be loaded without error.
Returns t if loadable, nil if not (e.g., missing dependencies)."
  (condition-case nil
      (progn
        (literate-elisp-load file)
        t)
    (file-missing nil)
    (error nil)))

;;; ============================================================================
;;; Symbol Verification
;;; ============================================================================

(defun test-static--check-symbol-bound (type name)
  "Check if symbol NAME is bound according to TYPE.
Returns nil if bound, or an error message string if not."
  (cond
   ;; Functions: defun, defmacro, defsubst, cl-defun, etc.
   ((memq type '(defun defmacro defsubst cl-defun cl-defmacro cl-defsubst
                       defadvice define-advice cl-defgeneric cl-defmethod))
    (unless (fboundp name)
      (format "Function `%s' not defined (expected from %s)" name type)))
   ;; Variables: defvar, defconst, defcustom
   ((memq type '(defvar defconst defcustom defvar-local))
    (unless (boundp name)
      (format "Variable `%s' not defined (expected from %s)" name type)))
   ;; defface - faces are special and checked differently
   ((eq type 'defface)
    (unless (facep name)
      (format "Face `%s' not defined (expected from defface)" name)))
   ;; defgroup doesn't create a bound variable - it just registers with customize
   ((eq type 'defgroup)
    nil)  ; Always pass - defgroup doesn't create variables
   ;; define-error creates error symbols but they might not be boundp
   ((eq type 'define-error)
    nil)  ; Always pass - define-error handled differently
   ;; Aliases
   ((eq type 'defalias)
    (unless (fboundp name)
      (format "Alias `%s' not defined" name)))
   ;; Default: check either fboundp or boundp
   (t
    (unless (or (fboundp name) (boundp name))
      (format "Symbol `%s' not bound (expected from %s)" name type)))))

;;; ============================================================================
;;; Byte Compilation Helpers
;;; ============================================================================

(defun test-static--byte-compile-string-strict (elisp-string)
  "Byte-compile ELISP-STRING with strict warnings.
Returns list of warning/error messages."
  (let ((temp-file (make-temp-file "elisp-lint" nil ".el"))
        (byte-compile-warnings t)
        (byte-compile-error-on-warn nil)
        (warnings nil))
    (unwind-protect
        (progn
          (with-temp-file temp-file
            (insert elisp-string))
          ;; Clear compile log
          (with-current-buffer (get-buffer-create "*Compile-Log*")
            (let ((inhibit-read-only t))
              (erase-buffer)))
          ;; Compile
          (byte-compile-file temp-file)
          ;; Extract warnings
          (when-let ((log-buf (get-buffer "*Compile-Log*")))
            (with-current-buffer log-buf
              (goto-char (point-min))
              (while (re-search-forward "^.*\\(?:Warning\\|Error\\).*$" nil t)
                (push (match-string 0) warnings)))))
      ;; Cleanup
      (when (file-exists-p temp-file)
        (delete-file temp-file))
      (when (file-exists-p (concat temp-file "c"))
        (delete-file (concat temp-file "c"))))
    (nreverse warnings)))

(defvar test-static--known-external-symbols
  '(;; Optional external packages
    "company-begin-backend" "company-grab-symbol"
    ;; Cross-module references (loaded at runtime)
    "emacs-mcp-server-running-p" "emacs-mcp-server-start" "emacs-mcp-server-port"
    "claude-org--insert-block-menu-dynamic"
    ;; Emacs version-specific functions
    "parse-iso8601-time-string"
    ;; Intentionally forward-referenced
    "claude-agent-cleanup"
    ;; Struct accessors referenced before struct is parsed
    "claude-agent-pre-tool-use-input-tool-name"
    "claude-agent-pre-tool-use-input-tool-input"
    ;; Variables defined in claude-org.org but referenced in claude-agent.org
    "claude-agent-translate-model")
  "List of symbol names known to be external or forward-referenced.
These are excluded from byte-compile undefined warnings.")

(defun test-static--filter-undefined-warnings (warnings)
  "Filter WARNINGS to only include undefined function/variable warnings.
Excludes known external dependencies."
  (seq-filter
   (lambda (w)
     (and (or (string-match-p "not known to be defined" w)
              (string-match-p "reference to free variable" w)
              (string-match-p "the function .* is not known" w)
              (string-match-p "void-function" w)
              (string-match-p "void-variable" w))
          ;; Exclude known external symbols
          (not (seq-some (lambda (sym) (string-match-p sym w))
                         test-static--known-external-symbols))))
   warnings))

;;; ============================================================================
;;; Tests
;;; ============================================================================

(ert-deftest test-static-all-definitions-bound ()
  "Verify all definitions in .org files are bound after loading.
This dynamically extracts all defun, defvar, cl-defstruct, etc. from
source files and checks they are properly defined."
  :tags '(:static :lint)
  (require 'literate-elisp)
  (let* ((root (test-static--find-project-root))
         (org-files (test-static--find-org-source-files root))
         (loadable-files nil)
         (all-errors nil))
    ;; First pass: try to load all files, track which ones succeed
    (dolist (file org-files)
      (condition-case err
          (progn
            (literate-elisp-load file)
            (push file loadable-files))
        (file-missing
         (if test-static--skip-files-without-deps
             (message "Skipping %s (missing dependency: %s)"
                      (file-name-nondirectory file) (caddr err))
           (push (format "Failed to load %s: missing %s"
                         (file-name-nondirectory file) (caddr err))
                 all-errors)))
        (error
         (push (format "Failed to load %s: %s"
                       (file-name-nondirectory file) err)
               all-errors))))
    ;; Now extract and verify definitions from loadable files only
    (dolist (file (nreverse loadable-files))
      (let* ((elisp-string (test-static--extract-elisp-from-org file))
             (raw-defs (test-static--extract-definitions-from-string elisp-string))
             (definitions (test-static--expand-definitions raw-defs elisp-string))
             (file-errors nil))
        (dolist (def definitions)
          (let ((type (car def))
                (name (cdr def)))
            ;; Skip certain generated symbols that may not exist
            (unless (or (string-suffix-p "-map" (symbol-name name))  ; keymaps optional
                        (string-suffix-p "-hook" (symbol-name name))) ; hooks optional
              (when-let ((err (test-static--check-symbol-bound type name)))
                (push (format "%s: %s" (file-name-nondirectory file) err)
                      file-errors)))))
        (setq all-errors (append file-errors all-errors))))
    ;; Report errors
    (when all-errors
      (ert-fail
       (format "Found %d undefined symbols:\n  %s"
               (length all-errors)
               (mapconcat #'identity (seq-take all-errors 20) "\n  "))))))

(ert-deftest test-static-byte-compile-no-undefined ()
  "Byte-compile source files and check for undefined references.
This catches issues that only manifest during compilation."
  :tags '(:static :lint :slow)
  (require 'literate-elisp)
  (let* ((root (test-static--find-project-root))
         (org-files (test-static--find-org-source-files root))
         (loadable-files nil)
         (all-warnings nil))
    ;; Load files first to define symbols, track loadable ones
    (dolist (file org-files)
      (condition-case nil
          (progn
            (literate-elisp-load file)
            (push file loadable-files))
        (file-missing
         (when test-static--skip-files-without-deps
           (message "Skipping byte-compile for %s (missing deps)"
                    (file-name-nondirectory file))))
        (error nil)))
    ;; Compile only loadable files
    (dolist (file (nreverse loadable-files))
      (let* ((elisp-string (test-static--extract-elisp-from-org file))
             (warnings (test-static--byte-compile-string-strict elisp-string))
             (undefined (test-static--filter-undefined-warnings warnings)))
        (dolist (w undefined)
          (push (format "%s: %s" (file-name-nondirectory file) w) all-warnings))))
    ;; Report
    (when all-warnings
      (ert-fail
       (format "Byte-compile found %d undefined references:\n  %s"
               (length all-warnings)
               (mapconcat #'identity (seq-take all-warnings 20) "\n  "))))))

(ert-deftest test-static-check-declare-valid ()
  "Verify all declare-function statements are valid."
  :tags '(:static :lint)
  (require 'check-declare)
  (let* ((root (test-static--find-project-root))
         (el-files (directory-files root t "\\.el$"))
         (errors nil))
    (dolist (file el-files)
      (when (file-exists-p file)
        (condition-case err
            (let ((file-errors (check-declare-file file)))
              (when file-errors
                (push (cons (file-name-nondirectory file) file-errors) errors)))
          (error
           (push (format "%s: check-declare error: %s"
                         (file-name-nondirectory file) err)
                 errors)))))
    (when errors
      (ert-fail (format "check-declare errors:\n%S" errors)))))

(ert-deftest test-static-features-loadable ()
  "Test that all source files can be loaded without error.
Files with missing optional dependencies are skipped if
`test-static--skip-files-without-deps' is non-nil."
  :tags '(:static :lint)
  (require 'literate-elisp)
  (let* ((root (test-static--find-project-root))
         (org-files (test-static--find-org-source-files root))
         (errors nil)
         (loaded 0))
    (dolist (file org-files)
      (condition-case err
          (progn
            (literate-elisp-load file)
            (cl-incf loaded))
        (file-missing
         (if test-static--skip-files-without-deps
             (message "Skipping %s (missing: %s)"
                      (file-name-nondirectory file) (caddr err))
           (push (format "%s: missing %s"
                         (file-name-nondirectory file) (caddr err))
                 errors)))
        (error
         (push (format "%s: %s" (file-name-nondirectory file) err) errors))))
    (when errors
      (ert-fail
       (format "Failed to load:\n  %s"
               (mapconcat #'identity errors "\n  "))))
    ;; Ensure at least some files loaded
    (should (> loaded 0))))

(ert-deftest test-static-no-duplicate-definitions ()
  "Check for duplicate symbol definitions across different files.
Same-file duplicates are ignored (often example code or intentional redefs)."
  :tags '(:static :lint :style)
  (let* ((root (test-static--find-project-root))
         (org-files (test-static--find-org-source-files root))
         (all-defs (make-hash-table :test 'equal))
         (cross-file-duplicates nil))
    (dolist (file org-files)
      (let* ((elisp-string (test-static--extract-elisp-from-org file))
             (defs (test-static--extract-definitions-from-string elisp-string))
             (file-short (file-name-nondirectory file)))
        (dolist (def defs)
          (let* ((name (cdr def))
                 (name-str (symbol-name name))
                 (existing (gethash name-str all-defs)))
            (cond
             ;; Same file duplicate - skip (often intentional)
             ((and existing (string= existing file-short))
              nil)
             ;; Cross-file duplicate - record it
             (existing
              (push (format "`%s' defined in both %s and %s"
                            name-str existing file-short)
                    cross-file-duplicates))
             ;; First occurrence
             (t
              (puthash name-str file-short all-defs)))))))
    ;; Only fail on cross-file duplicates
    (when cross-file-duplicates
      (ert-fail
       (format "Found %d cross-file duplicate definitions:\n  %s"
               (length cross-file-duplicates)
               (mapconcat #'identity (seq-take cross-file-duplicates 10) "\n  "))))))

;;; ============================================================================
;;; Utility: Show all definitions (for debugging)
;;; ============================================================================

(defun test-static-list-all-definitions ()
  "List all definitions found in project source files.
Useful for debugging and inspection."
  (interactive)
  (require 'literate-elisp)
  (let* ((root (test-static--find-project-root))
         (org-files (test-static--find-org-source-files root))
         (buf (get-buffer-create "*Elisp Definitions*")))
    (with-current-buffer buf
      (erase-buffer)
      (insert "Elisp Definitions\n")
      (insert "=================\n\n")
      (dolist (file org-files)
        (let* ((elisp-string (test-static--extract-elisp-from-org file))
               (raw-defs (test-static--extract-definitions-from-string elisp-string))
               (defs (test-static--expand-definitions raw-defs elisp-string)))
          (insert (format "## %s (%d definitions)\n\n"
                          (file-name-nondirectory file)
                          (length defs)))
          ;; Group by type
          (let ((by-type (make-hash-table)))
            (dolist (def defs)
              (push (cdr def) (gethash (car def) by-type)))
            (maphash
             (lambda (type symbols)
               (insert (format "### %s (%d)\n" type (length symbols)))
               (dolist (sym (sort symbols (lambda (a b)
                                            (string< (symbol-name a)
                                                     (symbol-name b)))))
                 (let ((bound (if (or (fboundp sym) (boundp sym)) "+" "-")))
                   (insert (format "  %s %s\n" bound sym))))
               (insert "\n"))
             by-type))
          (insert "\n"))))
    (pop-to-buffer buf)))

(provide 'test-static-analysis)
;;; test-static-analysis.el ends here
