"""Generate INDEX.org from Python LP .org source files.

Scans ``claude-agent-python.org`` for sections with ``:tangle`` properties
that target ``python/claude_agent/*.py`` and writes a summary table to
stdout (or a file).

Designed to be invoked from ``make build-python-index``.

Output format: an org table with columns Module | Source | Heading | Line | Tangle | CUSTOM_ID.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

HEADING_RE = re.compile(r"^(\*+)\s+(.*?)\s*$")
TANGLE_RE = re.compile(r":tangle\s+(\S+)")
MODULE_RE = re.compile(r":LITERATE_ORG_MODULE:\s+(\S+)")
CUSTOM_ID_RE = re.compile(r":CUSTOM_ID:\s+(\S+)")


@dataclass
class Entry:
    module: str
    source: str
    heading: str
    line: int
    tangle: str
    custom_id: str


def scan(path: Path) -> list[Entry]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    entries: list[Entry] = []

    current_heading = ""
    current_heading_line = 0
    current_tangle = ""
    current_module = ""
    current_custom_id = ""
    in_properties = False

    for idx, line in enumerate(lines, start=1):
        hm = HEADING_RE.match(line)
        if hm:
            # Flush previous section if it had a tangle target
            if current_tangle and "python/claude_agent/" in current_tangle:
                module = current_module or _tangle_to_module(current_tangle)
                entries.append(
                    Entry(
                        module=module,
                        source=path.name,
                        heading=current_heading,
                        line=current_heading_line,
                        tangle=current_tangle,
                        custom_id=current_custom_id,
                    )
                )
            current_heading = hm.group(2).strip()
            current_heading_line = idx
            current_tangle = ""
            current_module = ""
            current_custom_id = ""
            in_properties = False

        if ":PROPERTIES:" in line:
            in_properties = True
        if ":END:" in line:
            in_properties = False

        if in_properties:
            tm = TANGLE_RE.search(line)
            if tm:
                current_tangle = tm.group(1)
            mm = MODULE_RE.search(line)
            if mm:
                current_module = mm.group(1)
            cm = CUSTOM_ID_RE.search(line)
            if cm:
                current_custom_id = cm.group(1)

    # Flush last section
    if current_tangle and "python/claude_agent/" in current_tangle:
        module = current_module or _tangle_to_module(current_tangle)
        entries.append(
            Entry(
                module=module,
                source=path.name,
                heading=current_heading,
                line=current_heading_line,
                tangle=current_tangle,
                custom_id=current_custom_id,
            )
        )

    return entries


def _tangle_to_module(tangle: str) -> str:
    """Convert a tangle path like ./python/claude_agent/foo.py to module name."""
    m = re.search(r"python/claude_agent/(.+)\.py", tangle)
    if m:
        return "python/claude_agent." + m.group(1).replace("/", ".")
    return tangle


def render_index(entries: list[Entry]) -> str:
    """Render entries as an org table."""
    out = [
        "#+TITLE: Python Agent SDK Module Index",
        "#+OPTIONS: toc:nil num:nil",
        "",
        "Generated by =scripts/build_index.py=.  Do not edit by hand.",
        "",
        "| Module | Source | Heading | Line | Tangle | CUSTOM_ID |",
        "|--------+--------+---------+------+--------+-----------|",
    ]
    for e in sorted(entries, key=lambda e: e.module):
        heading_link = f"[[file:{e.source}::{e.line}][={e.heading}=]]"
        custom_id = f"={e.custom_id}=" if e.custom_id else ""
        out.append(
            f"| ={e.module}= | ={e.source}= | {heading_link} | {e.line} | ={e.tangle}= | {custom_id} |"
        )
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    targets = [Path(p) for p in argv[1:]]
    if not targets:
        targets = [Path("claude-agent-python.org")]

    all_entries: list[Entry] = []
    for target in targets:
        if not target.exists():
            print(f"build-index: {target} not found", file=sys.stderr)
            return 1
        all_entries.extend(scan(target))

    output = render_index(all_entries)

    # Write to INDEX-python.org (not INDEX.org to avoid collision with any future LP index)
    out_path = Path("INDEX-python.org")
    out_path.write_text(output, encoding="utf-8")
    print(f"build-index: wrote {out_path} ({len(all_entries)} modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
